Update action workflow

diff --git a/.github/workflows/check-notebooks.yml b/.github/workflows/check-notebooks.yml
--- a/.github/workflows/check-notebooks.yml
+++ b/.github/workflows/check-notebooks.yml
@@ -33,9 +33,34 @@ jobs:
             sleep 1
           done
 
-      - name: Run all selected notebooks
+      - name: Test all notebooks other than those excluded
         run: |
-          cd 00_notebooks && \
+          cd 00_notebooks
+          mkdir -p papermill-out
           find . -name "*.ipynb" | \
-          grep -vFf <(grep -v -e '^#' -e '^$' ../.github/workflows/notebooks_to_exclude.txt) | \
-          xargs -I {} docker exec $(docker ps -q --filter expose=8888) papermill "/home/jovyan/notebooks/{}"
+            grep -vFf <(grep -v -e '^#' -e '^$' ../.github/workflows/notebooks_to_exclude.txt) | \
+            xargs -I {} docker exec $(docker ps -q --filter expose=8888) \
+              papermill "/home/jovyan/notebooks/{}" \
+                        "/home/jovyan/notebooks/papermill-out/{}"
+          # Look for failures
+          mkdir -p papermill-out/failed
+          for file in $(grep -r -l "papermill-error-cell-tag" papermill-out); do
+            mv "$file" papermill-out/failed
+            echo "Notebook failed: $file"
+          done
+
+          # Set the exit code based on whether we detected any failures
+          if [ "$(ls -A papermill-out/failed)" ]; then
+            echo "Failing notebooks found"
+            exit 1
+          else
+            echo "No failures found"
+          fi
+
+      - name: Store any failing test artifacts
+        uses: actions/upload-artifact@v3
+        if: ${{ failure() }}
+        with:
+          name: papermill-output
+          path: |
+            00_notebooks/papermill-out/failed
